include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

linter:
  rules:
    # enforce const constructors where possible
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    # catch unnecessary rebuilds
    use_key_in_widget_constructors: true
