name: campus_bites
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.5
  dio: ^5.8.0+1
  firebase_analytics: ^11.4.4
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_performance: ^0.10.1+4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.11.0
  google_sign_in: ^6.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  permission_handler: ^12.0.0+1
  geolocator: ^14.0.0
  responsive_builder: ^0.7.1
  shared_preferences: ^2.0.10
  url_launcher: ^6.1.7
  isar: ^3.1.0+1
  isar_flutter_libs:
    git: 
      url: https://github.com/MrLittleWhite/isar_flutter_libs.git
  path_provider: ^2.1.5
  lru_cache: ^0.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^5.0.2

dependency_overrides:
  geolocator_android: 4.3.3

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.png
    - assets/placeholder.png