name: campus_bites
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cloud_firestore: ^5.6.5
  dio: ^5.8.0+1
  firebase_analytics: ^11.4.4
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_performance: ^0.10.1+4
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.11.0
  permission_handler: ^11.4.0
  google_sign_in: ^6.3.0
  intl: ^0.18.0
  logger: ^2.5.0
  responsive_builder: ^0.7.1
  url_launcher: ^6.1.7
  shared_preferences: ^2.0.10

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.png
    - assets/placeholder.png